# 1) Configuration de build
[build]
  command = "npm run build"   # Commande de build
  publish = "dist"            # Dossier à publier après le build

# 2) Redirection pour les SPA (Single Page App)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 3) En-têtes personnalisés (headers)
[[headers]]
  # S’applique à tous les chemins
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# 4) Variables d’environnement générales (tous les builds)
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.0"

# 5) Configuration spécifique au contexte de production
[context.production]
  # Variables d’environnement uniquement pour la production
  [context.production.environment]
    NODE_ENV = "production"
    SITE_URL = "https://mrcenpoche.xyz"
